
import EnumValue = require('dw/value/EnumValue')
import MarkupText = require('dw/content/MarkupText');
import MediaFile = require('dw/content/MediaFile');

// autogeneratedfile - '/Users/ryanlambert/Projects/Repos/dispatch-sfcc-b2c-cartridge/metadata/site-import-dispatch/meta/system-objecttype-extensions.xml'
declare global {
    module ICustomAttributes {

		interface Order {
			/**
			* Payment Error Message
			* 
			* @source [attribute](file:/Users/ryanlambert/Projects/Repos/dispatch-sfcc-b2c-cartridge/metadata/site-import-dispatch/meta/system-objecttype-extensions.xml#6) 
			*/
			Dispatch_paymentErrorMessage: string | null;

		}
	}
}

declare global {
	interface IGetCustomPreferenceValue {
		
	}
}